package it.micro.saga;

public enum Status {
    NOT_READY,
    READY,
    PENDING,
    SUCCESS,
    FAILURE,
    COMPENSATION,
    COMPENSATION_COMPLETE,
    COMPENSATION_FAILED,
    COMPENSATION_SUCCEEDED,
    NOT_FOUND
}
